# Generated by Django 3.2.9 on 2021-11-08 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutedCmd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.CharField(max_length=1024)),
                ('exec_time', models.DateTimeField(default=datetime.datetime(2021, 11, 8, 9, 11, 5, 266863))),
            ],
        ),
    ]
