# Generated by Django 3.2.9 on 2021-11-08 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wincmd', '0003_alter_executedcmd_exec_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='executedcmd',
            name='out',
            field=models.CharField(default='nil', max_length=1024),
        ),
        migrations.AlterField(
            model_name='executedcmd',
            name='exec_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 23, 56, 50, 802564)),
        ),
    ]
